### ISSUE TITLE
I do not have the option to create Project at hp-danbif

### ISSUE THREAD

**Issue by DanBIF** [gbif/hp-danbif#1]
**Describe the bug**
At https://github.com/gbif/hp-danbif/projects?query=is%3Aopen I miss the option to  create a project where I want to keep my work tasks to buil the Danish hosted portal

**To Reproduce**
1. Go to https://github.com/gbif/hp-danbif/projects?query=is%3Aopen
There is no "new project" option
![image](https://github.com/user-attachments/assets/b8b538aa-3853-40a9-b2d1-86ed7ba9b0b4)

**Expected behavior**
Have option to create project
![image](https://github.com/user-attachments/assets/c4086793-a975-456d-a92e-cfe1ef90c149)

**Desktop (please complete the following information):**
 - Browser: Chrome 

**Comments**
If creating projects here represents a problem, I can go and keep tasks in my own repo

**Comment by MortenHofft** [comment]
Apparently projects sit under the repository organisation. in theis case GBIF.
https://github.com/orgs/gbif/projects/25/views/1

**Comment by DanBIF** [comment]
I get a 404 for the link https://github.com/orgs/gbif/projects/25/views/1 I will carry on in own repo and create actual issues that need solving in this repo

**Comment by MortenHofft** [comment]
Apparently I needed to make you admin of the project as well. But above sounds like a fine approach. Let me know if it is causing you issues
